### ISSUE TITLE
Common words don't get opacity applied

### ISSUE THREAD

**Issue by spaceandrew** [ahrm/chrome-fastread#11]
<img width="889" alt="Screen Shot 2022-05-22 at 12 27 26 AM" src="https://user-images.githubusercontent.com/10898392/169678626-1f5c7bc0-4b47-4624-ae1c-b2c50fbfd756.png">

Common words like "the", "of", etc don't get the opacity setting applied.

**Comment by ahrm** [comment]
From readme:

> The first character can be either - or +. If it is -, we don't highlight common english words (for example 'a', 'and', etc.) if it is '+' we highlight all words.

**Comment by spaceandrew** [comment]
> From readme:
> 
> > The first character can be either - or +. If it is -, we don't highlight common english words (for example 'a', 'and', etc.) if it is '+' we highlight all words.

This has nothing to do with bolding the words, it's about the opacity. If you don't bold the common words to skip over them, then the "skip" opacity should be applied as well.

**Comment by johnkershaw** [comment]
So [trying to clarify your example]... you're saying that the words 'the' and 'of' in the screenshot should be mostly transparent, but they're showing as 'normal' weight and full opacity.
