### ISSUE TITLE
Unicode hex character codes displayed on websites

### ISSUE THREAD

**Issue by chris-pilcher** [ahrm/chrome-fastread#16]
Thanks for this awesome extension! I installed it today and noticed that it sometimes shows Unicode hex character codes on websites:

E.g. on Google search results [`&#x2f;`](https://www.codetable.net/hex/2f) is displayed for `/`:

![image](https://user-images.githubusercontent.com/7553472/171077389-04311723-ef9f-443a-b47d-eb98c6d6133c.png)

**Comment by ahrm** [comment]
I guess this was caused by the recent pull request the prevent XSS here: https://github.com/ahrm/chrome-fastread/pull/15. I have reverted it in e765ce7fb1aace32fbbf1d375108d5d49107e654.
