### ISSUE TITLE
cannot disable auto apply

### ISSUE THREAD

**Issue by andycjw** [ahrm/chrome-fastread#19]
automatic mode is always on even after trying to toggle the mode into red and green button status, how do I troubleshoot this

**Comment by andycjw** [comment]
just realized the one I installed from chrome extension store is not using the same updated code on this github

https://chrome.google.com/webstore/detail/astrospeed-read-5x-faster/lbmambbnglofgbcaphmokiadbfdicddj

their tab update listener doesn't check for autoApply

```
chrome.tabs.onUpdated.addListener(async (tabId, changeInfo)=>{
    if (changeInfo.status == 'complete'){
      let [tab] = await chrome.tabs.query({active: true, currentWindow: true});
      chrome.scripting.executeScript({
          target: {tabId: tab.id},
          function: fastreadifyPage,
      });
    }
});
```

is this astrospeed stealing code from you guys?

**Comment by ahrm** [comment]
> is this astrospeed stealing code from you guys?

Yes. I don't care though.
