### ISSUE TITLE
keybinding to toggle current page

### ISSUE THREAD

**Issue by ertwro** [ahrm/chrome-fastread#23]
This is an enhancement petition. A keybinding to toggle the current page. By the way I love sioyek.

**Comment by ahrm** [comment]
What do you mean by toggle?

**Comment by ertwro** [comment]
When one uses the chrome-fastread extension in order to use it one has to click the extension and the click a button that’s literally called “toggle page”.
Since clicking is far slower than a key binding to activate it, that’s what am asking. A keybinding to activate the function “toggle page”.
