### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AlejandroAkbal** [ahrm/chrome-fastread#5]
Could you set a License, please?

**Comment by ahrm** [comment]
I am not sure if I can use a license because I basically copied the idea from the hackernews post.

**Comment by BuyMyMojo** [comment]
I think since you wrote it into an actual extension with a little bit of UI you can license it

**Comment by AlejandroAkbal** [comment]
Yeah, the idea might be from HN, but the code is yours

**Comment by ahrm** [comment]
Added in 05281b7b7df504af984b0a4fb907097890ec4043.

**Comment by jomamaaye** [comment]
Looks like this repo (including the logo design) was copied and published as another extension, listed [here](https://chrome.google.com/webstore/detail/bionic-reading-digest-pas/lbmambbnglofgbcaphmokiadbfdicddj/). @ahrm are you affiliated with the developer of this extension?

**Comment by ahrm** [comment]
No, but I don't care. It is a little scummy that they didn't even link to this repo though.
